src/Proyecto_G8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('preguntas/', include('apps.preguntas.urls')),
    path('partidas/', include('apps.partidas.urls')),
    path('', include('apps.usuarios.urls')),
] 


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/apps/partidas/urls.py
from django.urls import path
from . import views

app_name = "partidas"

urlpatterns = [
	path('jugar/', views.jugar, name="jugar"),
	path('resultado/', views.resultado, name="resultado"),
	path('', views.listar, name="listar"),
	
]

src/apps/preguntas/urls.py
from django.urls import path
from . import views

app_name = "preguntas"

urlpatterns = [
	path('crear/', views.crear, name="crear"),
	path('crear/guardar', views.guardar, name="guardar"),
	path('eliminar/<int:pk>/', views.eliminar, name="eliminar"),
	path('', views.listar, name="listar"),
]

src/apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = "usuarios"

urlpatterns = [
	path('', views.inicio, name='inicio'),
    path('login/', views.loguear, name="login"),
    path('logout/', views.desloguear, name="logout"),
    path('registro/', views.registrar, name="registro"),
	path('usuarios/', views.listar, name="listar"),
	path('usuarios/editar/<int:pk>/', views.EditarUsuario.as_view(), name="editar"),
	path('usuarios/crear/', views.crear, name="crear_usuario"),
]

src/templates/base/base.html
{% load static %}

<!DOCTYPE html>

<html>
	<head>
		<meta charset="utf-8">
		<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">	
		<title>TRABAJO FINAL G8</title>
		

		{# bootstrap styles #}
		<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
		<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  	
  	{#ICONO#}
    <link rel="shortcut icon" type="image/png" href="{% static 'info2.png' %}"/>

		{# fonts #}
		<link rel="preconnect" href="https://fonts.googleapis.com">
		<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
		<link href="https://fonts.googleapis.com/css2?family=Bebas+Neue&display=swap" rel="stylesheet">
		<link href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,200;0,400;0,700;1,200;1,400;1,700&display=swap" rel="stylesheet">

		<style>
      body{
        background: url('{% static "informatorio1.png" %}')no-repeat center center fixed;
  			background-position: right bottom ; 
        display:flex;
       	flex-direction: column;
        justify-content: center;
        }

        footer {
        	bottom: 0;
        	position: fixed;
				  height:50px;
				  width:100%;
				  background-color: #ff000000;	
				}
    </style>

	</head>

	<body>

		{% if user.is_authenticated  %}

		<header class="d-flex justify-content-between mx-5 my-3">

			<ul class="nav nav-tabs">
				{% if user.es_admin or user.is_superuser %}

			  		<li class="nav-item">
			  		  <a class="nav-link" href="{% url 'usuarios:listar' %}"><i class="bi bi-person-fill"></i>Usuarios</a>
			 		</li>
			  		<li class="nav-item">
			  		  <a class="nav-link" href="{% url 'preguntas:listar' %}"><i class="bi bi-question-lg"></i>Preguntas</a>
				  </li>
				{% else %}
					<li class="nav-item">
						<a class="nav-link active" href="{% url 'usuarios:inicio' %}">
				  		<i class="bi bi-house-fill"></i>Home</a>
					</li> 
			 		<li class="nav-item">
			  	  		<a class="nav-link" href="{% url 'partidas:listar' %}"><i class="bi bi-check-lg"></i>Partidas</a>
			 		</li>
				{% endif %}	  
		  </ul>
  		<a class="nav-link disabled " href="{% url 'usuarios:logout' %}"><i class="bi bi-door-open-fill"></i>Salir</a>
		</header>
		{% endif %}

		<main class="container">
			{% block contenido %}
			
			{% endblock contenido %}
		</main>	


		{# bootstrap scripts #}
		<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
		</script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous">
    </script>
			

			

	</body>

	
</html>