src/Proyecto_G8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('preguntas/', include('apps.preguntas.urls')),
    path('partidas/', include('apps.partidas.urls')),
    path('', include('apps.usuarios.urls')),
] 


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/apps/preguntas/urls.py
from django.urls import path
from . import views

app_name = "preguntas"

urlpatterns = [
	path('crear/', views.crear, name="crear"),
	path('crear/guardar', views.guardar, name="guardar"),
	path('eliminar/<int:pk>/', views.eliminar, name="eliminar"),
	path('', views.listar, name="listar"),
]

src/apps/preguntas/models.py
from django.db import models
from django.db.models.deletion import CASCADE
from apps.usuarios.models import Usuario
import random

class Pregunta(models.Model):
    texto_pregunta = models.CharField(max_length=255)
    nivel = models.IntegerField()

    class Meta:
        db_table = 'Pregunta'

    def __str__(self):
        return self.texto_pregunta

    def get_respuestas(self):
        # traer todas las respuestas relacionadas a esta pregunta
        respuestas = self.respuesta_set
        # filtrar las incorrectas, crear una lista con sus ids y randomizarlos
        ids = [i.id for i in respuestas.filter(es_correcta = False)]
        random.shuffle(ids)
        # tomar muestra de 2 incorrectas
        subset = ids[:2]
        # buscamos la correcta
        correcta = respuestas.get(es_correcta = True)
        # agregamos el id de la correcta a la lista de incorrectas
        subset.append(correcta.id)
        # mezclamos de nuevo
        random.shuffle(subset)
        # devolvemos los objetos de los ids como nos quedaron
        return [respuestas.get(pk=i) for i in subset]

class Partida(models.Model):
    usuario = models.ForeignKey(Usuario, on_delete = models.CASCADE)
    fecha = models.DateTimeField(auto_now_add = True)
    puntos = models.IntegerField()
   
    class Meta:
        db_table = 'Partida'

class Respuesta(models.Model):
    texto_respuesta = models.CharField(max_length=255)
    pregunta = models.ForeignKey(Pregunta, on_delete = models.CASCADE)
    es_correcta = models.BooleanField(default=False)

    class Meta:
        db_table = 'Respuesta'

    def __str__(self):
        return self.texto_respuesta

src/apps/preguntas/forms.py
from django import forms
from .models import Pregunta, Respuesta

class PreguntaForm (forms.ModelForm):
	class Meta:
		model = Pregunta
		fields = [ 
			'texto_pregunta', 
			'nivel'
		]

class RespuestaForm (forms.ModelForm):
	class Meta:
		model = Respuesta
		fields = [ 
			'texto_respuesta'
		]

src/apps/preguntas/views.py
from django.shortcuts import render, redirect
from .models import Pregunta
from .forms import PreguntaForm, RespuestaForm
from django.views.generic import CreateView
from django.contrib.auth.decorators import login_required, user_passes_test
from utils.user_test import es_admin

@login_required()
@user_passes_test(es_admin, login_url = '', redirect_field_name = None)
def listar(request):
    template_name = "preguntas/listar.html"
    preguntas = Pregunta.objects.all()

    ctx = {
        'preguntas' : preguntas
    }    

    return render(request, template_name, ctx)

@login_required
@user_passes_test(es_admin, login_url = '/preguntas/', redirect_field_name = None)
def crear(request):
    template_name = "preguntas/crear.html"
    
    ctx = { 
        'form': PreguntaForm(),
        'completo': False,
        'tipo': 'incorrecta'
    }

    if request.method == "POST":
        ctx['form'] = RespuestaForm()

        if 'pregunta' not in request.session:
            request.session['pregunta'] = request.POST
            ctx['tipo'] = 'correcta'
        elif 'respuesta_correcta' not in request.session:
            request.session['respuesta_correcta'] = request.POST
        elif 'respuestas_incorrectas1' not in request.session:
            request.session['respuestas_incorrectas1']= [request.POST]
            ctx['completo'] = True
        else:
            request.session['respuestas_incorrectas2']=[request.POST]
            ctx['completo'] = True
    else:
        ctx['tipo'] = 'pregunta'
        for key in ['pregunta', 'respuesta_correcta', 'respuestas_incorrectas1','respuestas_incorrectas2']:
            quitar_de_session(request, key)

    return render(request,template_name, ctx)

@login_required
@user_passes_test(es_admin, login_url = '/preguntas/', redirect_field_name = None)
def guardar(request):
    pregunta = extraer_data(request, 'pregunta')
    if pregunta is not None:
        texto_pregunta = pregunta.get('texto_pregunta')
        nivel = pregunta.get('nivel')
        p = Pregunta.objects.create(texto_pregunta = texto_pregunta, nivel = nivel)

        correcta = extraer_data(request, 'respuesta_correcta')
        if correcta is not None:
            crear_respuesta(p, correcta, True)

        incorrectas = extraer_data(request, 'respuestas_incorrectas1')
        if incorrectas is not None:
            for incorrecta in incorrectas:
                crear_respuesta(p, incorrecta, False)
        incorrectas = extraer_data(request, 'respuestas_incorrectas2')
        if incorrectas is not None:
            for incorrecta in incorrectas:
                crear_respuesta(p, incorrecta, False)

    return redirect('preguntas:listar')


def extraer_data(request, key):
    if key in request.session:
        data = request.session[key]
        del request.session[key]
        return data

def crear_respuesta(pregunta, respuesta, correcta):
    if respuesta is not None:
        texto_respuesta = respuesta.get('texto_respuesta')
        print(pregunta.respuesta_set.create(texto_respuesta = texto_respuesta, es_correcta = correcta))

def quitar_de_session(request, key):
    if key in request.session:
        del request.session[key]

def eliminar(request, pk):
    p = Pregunta.objects.get(id=pk)
    p.delete()
    return redirect("preguntas:listar")

src/templates/preguntas/crear.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block contenido %}
    <h1>Crear pregunta: </h1>

    <form method="POST">{% csrf_token %}
      <div> 
        {{form|crispy}}

        <a href="{% url 'preguntas:listar' %}" class="btn btn-link mr-2">Cancelar</a>
        <button type="submit" class="btn btn-primary">
          {% if tipo == 'pregunta' %}
            Agregar pregunta
          {% elif tipo == 'correcta' %}
            Agregar respuesta correcta
          {% else %}
            Agregar respuesta incorrecta
          {% endif %}
        </button>

        {% if completo %}
          <a href="{% url 'preguntas:guardar' %}" class="btn btn-success mr-2">Enviar Formulario</a>
        {% endif %}
      </div>
    </form>
{% endblock contenido %}

src/templates/preguntas/listar.html
{% extends "base/base.html" %}{% load static %}

{% block contenido %}
    <a href="{% url 'preguntas:crear' %}" class="btn btn-secondary mr-2">Nueva Pregunta</a>
    <hr>
	<h1>Lista de Preguntas:</h1>
	<table class="table table-striped">
        <thead>
            <tr>
				<th>ID</th>
                <th>Pregunta</th>
                <th>     </th>
            </tr>
        </thead>
        <tbody>
            {% for p in preguntas %}
            <tr>
				<td>{{ p.id }}</td>
                <td>{{ p.texto_pregunta }}</td>
                <td>
                    <a href="{% url 'preguntas:eliminar' p.pk %}">Eliminar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock contenido %}