src/Proyecto_G8/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('preguntas/', include('apps.preguntas.urls')),
    path('partidas/', include('apps.partidas.urls')),
    path('', include('apps.usuarios.urls')),
] 


urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

src/apps/partidas/urls.py
from django.urls import path
from . import views

app_name = "partidas"

urlpatterns = [
	path('jugar/', views.jugar, name="jugar"),
	path('resultado/', views.resultado, name="resultado"),
	path('', views.listar, name="listar"),
	
]

src/apps/usuarios/urls.py
from django.urls import path
from . import views

app_name = "usuarios"

urlpatterns = [
	path('', views.inicio, name='inicio'),
    path('login/', views.loguear, name="login"),
    path('logout/', views.desloguear, name="logout"),
    path('registro/', views.registrar, name="registro"),
	path('usuarios/', views.listar, name="listar"),
	path('usuarios/editar/<int:pk>/', views.EditarUsuario.as_view(), name="editar"),
	path('usuarios/crear/', views.crear, name="crear_usuario"),
]

src/apps/usuarios/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class Usuario(AbstractUser):
    es_admin = models.BooleanField(default=False)
    
    class Meta:
        db_table = 'usuario'
	

src/juego/models.py
from django.db import models

# Create your models here.


class Usuario2(models.Model):
    nombre = models.CharField(max_length=50)
    nickname = models.CharField(max_length=50)
    email = models.EmailField()
    es_admin = models.BooleanField()
    puntaje = models.IntegerField()
    ult_acceso = models.DateField()
    partidas = models.ForeignKey('Partida', on_delete=models.CASCADE,)


class Partida(models.Model):
    puntos = models.IntegerField()
    cnt_respondidas = models.IntegerField()
    idusuario = models.ForeignKey('Usuario2', on_delete=models.CASCADE,)
    fecha = models.DateField()
    preguntas = models.ManyToManyField('Pregunta')

    class Meta:
        db_table = 'partida'

    def __str__(self):
        return self.nombre


class Pregunta(models.Model):
    texto_pregunta = models.CharField(max_length=255)
    id_partida = models.ManyToManyField('Partida')
    respuestas = models.ForeignField('Respuesta', on_delete=models.CASCADE,)

    class Meta:
        db_table = 'pregunta'

    def __str__(self):
        return self.nombre


class Respuesta(models.Model):
    id_pregunta = models.ForeignKey('Pregunta', on_delete=models.CASCADE,)
    es_correcta = models.BooleanField()
    texto_respuesta = models.CharField(max_length=255)

    class Meta:
        db_table = 'respueta'

    def __str__(self):
        return self.nombre

src/apps/usuarios/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from .models import Usuario

class RegistroUsuarioForm(UserCreationForm):
	class Meta: 
		model = Usuario
		fields = [
			"username",
			"email",
			"password1",
			"password2"
		] 

class CrearUsuarioForm(UserCreationForm):
	class Meta: 
		model = Usuario
		fields = [
			"username",
			"email",
			"password1",
			"password2",
			"es_admin"
		]

class EditForm(forms.ModelForm):
	class Meta:
		model = Usuario
		fields = [
			"username",
			"first_name",
			"last_name",
			"es_admin",
			"email",
		]

 

src/apps/usuarios/views.py
from django.shortcuts import render, redirect
from .forms import RegistroUsuarioForm, CrearUsuarioForm, EditForm
from .models import Usuario
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required, user_passes_test
from django.views.generic.edit import UpdateView
from utils.user_test import	es_admin
from django.urls import reverse_lazy

RUTA_INICIO = 'usuarios:inicio'
RUTA_LOGIN = 'usuarios:login'
RUTA_LISTAR_USUARIOS = 'usuarios:listar'

@login_required()
@user_passes_test(es_admin, login_url = '', redirect_field_name = None)
def listar(request):
	template_name = "usuarios/listar.html"
	usuarios = Usuario.objects.all()
	
	#para ver en consola los usuarios pasados (tamb lo puedo listar con un for)
	#print(lista_de_usuarios)

	#traer un usuario en especifico, ejemplo id=1
	#lista_de_usuarios = Usuario.objects.filter(id=1)

	ctx = {
		'usuarios': usuarios
	}	

	return render(request,template_name,ctx)

@login_required()
@user_passes_test(es_admin, login_url = '', redirect_field_name = None)
def crear(request):
	template_name = "usuarios/crear.html"
	form = CrearUsuarioForm()

	if request.method == 'POST':
		form = CrearUsuarioForm(request.POST)

		if form.is_valid():
			form.save()
			messages.success(request, 'La cuenta se ha creado exitosamente')
			return redirect(RUTA_LISTAR_USUARIOS)
		else:
			print(form.errors)

	ctx = { 'form': form }
	
	return render(request, template_name, ctx)


@login_required()
def inicio(request):
	template_name = "usuarios/inicio.html"
	return render(request, template_name, {})

def loguear(request):
    if request.user.is_authenticated:
        return redirect(RUTA_INICIO)

    ctx = {}

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
		
        if user is not None:
            login(request, user)
            url = RUTA_LISTAR_USUARIOS if es_admin(user) else RUTA_INICIO
            return redirect(url)
        else:
            ctx['error'] = 'Usuario o Password incorrecto'

    return render(request, "usuarios/login.html", ctx)

def registrar(request):
	if request.user.is_authenticated:
		return redirect(RUTA_INICIO)

	template_name = "usuarios/registro.html"
	form = RegistroUsuarioForm()

	if request.method == 'POST':
		form = RegistroUsuarioForm(request.POST)

		if form.is_valid():
			form.save()
			messages.success(request, 'Su cuenta se ha creado exitosamente')
			return redirect(RUTA_LOGIN)
		else:
			print(form.errors)

	ctx = { 'form': form }
	
	return render(request, template_name, ctx)

def editar(request,pk):
	template_name = "usuarios/editar.html"
	ctx = {
		'usuario': Usuario.objects.get(id=pk)
	}
	return render (request,template_name,ctx)

class EditarUsuario(UpdateView):
	model = Usuario
	template_name = "usuarios/editar.html"
	form_class = EditForm

	def get_success_url (self, **kwargs):
		return reverse_lazy("usuarios:listar")

@login_required()
def desloguear(request):
    logout(request)
    return redirect(RUTA_LOGIN)

src/templates/usuarios/crear.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block contenido %}
    <div class="row login-form justify-content-center">
        <h2 class="text-center col-12 my-4 border-bottom pb-3 text-uppercase">
            Crear nuevo usuario
        </h2>

        <form method="POST" class="col-12 col-md-4"> {% csrf_token %}
            {{ form|crispy }}

            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary mr-2">Crear cuenta</button>
            </div>
        </form>
    </div>
{% endblock contenido %}

src/templates/usuarios/editar.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block contenido %}
    <div class="row login-form justify-content-center">
        <h2 class="text-center col-12 my-4 border-bottom pb-3 text-uppercase">
            Editar usuario: {{usuario.first_name}} {{usuario.last_name}}
        </h2>

        <form method="POST" class="col-12 col-md-4"> {% csrf_token %}
            {{ form|crispy }}

            <div class="d-flex justify-content-center">
                <button type="submit" class="btn btn-primary mr-2">Editar</button>
            </div>
        </form>
    </div>
{% endblock contenido %}

src/templates/usuarios/inicio.html
{% extends "base/base.html" %}{% load static %}

{% block contenido %}
<div class="container d-flex align-items-center justify-content-center" style="height: 400px">
    <a class="btn btn-primary col-12 col-md-4 mx-1" href="{% url 'partidas:jugar' %}">Empezar Partida</a>
    <a class="btn btn-outline-primary col-12 col-md-4 mx-1" href="{% url 'partidas:listar' %}">Ver partidas jugadas</a>
</div>
{% endblock contenido %}

src/templates/usuarios/listar.html
{% extends "base/base.html" %}{% load static %}

{% block contenido %}
    <a href="{% url 'usuarios:crear_usuario' %}" class="btn btn-secondary mr-2">Nuevo Usuario</a>
    <hr>
	<h1>Lista de Usuarios:</h1>
	<table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nombre de usuario</th>
                <th>Email</th>
                <th>Admin</th>
                <th>Último ingreso</th>
                <th>Partidas</th>
                <th>     </th>
            </tr>
        </thead>
        <tbody>
            {% for u in usuarios %}
            <tr>
                <td>{{ u.id }}</td>
                <td>{{ u.username }}</td>
                <td>{{ u.email }}</td>
                <td>{{ u.es_admin }}</td>
                <td>{{ u.last_login }}</td>
                <td>{{ u.partida_set.count }}</td>
                <td>
                    <a href="{% url 'usuarios:editar' u.pk %}">Editar</a>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock contenido %}

src/templates/usuarios/login.html
{% extends "base/base.html" %}{% load static %} 

{% block contenido %}
	<div class="row login-form justify-content-center">
		<h2 class="text-center col-12 my-4 border-bottom pb-3 text-uppercase">
			Iniciar sesión
		</h2>

		<form method="POST" class="col-12 col-md-4"> {% csrf_token %}
			<div class="form-group">
				<label>Nombre de Usuario:</label>
				<input type="text" class="form-control" id="username" name="username">
			</div>

			<div class="form-group">
				<label>Contraseña</label>
				<input type="password" class="form-control" id="password" name="password">
			</div>

			{% if error %}
				<p class="text-center my-3 text-danger">{{ error }}</p>
			{% endif %}

			<div class="d-flex justify-content-center">
				<a href="{% url 'usuarios:registro' %}" class="btn btn-link mr-2">Registrarme</a>
				<button type="submit" class="btn btn-primary mr-2">Ingresar</button>
			</div>
		</form>
	</div>
{% endblock contenido %}

src/templates/usuarios/registro.html
{% extends "base/base.html" %}
{% load crispy_forms_tags %}

{% block contenido %}
{% load static %}
    <div class="row login-form justify-content-center">
        <h2 class="text-center col-12 my-4 border-bottom pb-3 text-uppercase">
            Registrarse
        </h2>

        <form method="POST" class="col-12 col-md-4"> {% csrf_token %}
            {{ form|crispy }}

            <div class="d-flex justify-content-center">
                <a href="{% url 'usuarios:login' %}" class="btn btn-link mr-2">Iniciar sesión</a>
                <button type="submit" class="btn btn-primary mr-2">Crear cuenta</button>
            </div>
        </form>
    </div>
{% endblock contenido %}